finish roman to integer
zoec0110/practice pull request #12
Opened 2022-10-04 06:01 UTC by zoec0110

完成 roman to integer作業

2022-10-06 09:43 UTC, hzchirs requested changes

2022-10-06 09:43 UTC, hzchirs commented on roman_to_integer.rb
> +    temp -= (map[arr[index - 1]]) * 2 if index != 0 && (map[arr[index - 1]] < map[arr[index]])
```suggestion
    temp -= (map[arr[index - 1]]) * 2 if index != 0 && (map[arr[index - 1]] < map[roman])
```

2022-10-07 02:11 UTC, zoec0110 commented on roman_to_integer.rb
> +    temp -= (map[arr[index - 1]]) * 2 if index != 0 && (map[arr[index - 1]] < map[arr[index]])
已經完成修正

2022-10-07 02:13 UTC, hzchirs approved these changes

2022-10-07 02:14 UTC, merged